# Generated by Django 5.2.8 on 2025-12-07 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_createdworkouts_excercises_delete_weight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excercises',
            name='weight',
        ),
        migrations.CreateModel(
            name='UsedWorkouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workoutid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.createdworkouts')),
            ],
        ),
        migrations.CreateModel(
            name='Weights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('excerciseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.excercises')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
