# Generated by Django 5.2.8 on 2025-12-07 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_excercises_weight_usedworkouts_weights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excercises',
            name='userid',
        ),
    ]
