# Generated by Django 5.2.8 on 2025-12-07 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_excercises_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='weights',
            name='workoutid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.createdworkouts'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UsedWorkouts',
        ),
    ]
