# Generated by Django 5.2.8 on 2025-12-07 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_weights_workoutid_delete_usedworkouts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='previousworkouts',
            name='workout_type',
        ),
        migrations.AddField(
            model_name='previousworkouts',
            name='workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.createdworkouts'),
        ),
    ]
