# Generated by Django 6.0 on 2025-12-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_previousworkouts_workout_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='previousworkouts',
            name='completed_sets',
            field=models.TextField(default='{}'),
        ),
    ]
